language: node_js
node_js:
- '4'
- '5'
env:
  - CXX=g++-4.8
sudo: false
dist: trusty
cache:
  apt: true
  directories:
    - node_modules
    - ffmpeg-2.1.3-64bit-static
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - google-chrome
    packages:
    - g++-4.8
    - google-chrome-stable
  firefox: latest
before_install:
- mkdir /tmp/ffmpeg
- wget http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz -O /tmp/ffmpeg/download-ffmpeg.tar.xz
- tar -xf /tmp/ffmpeg/download-ffmpeg.tar.xz -C /tmp/ffmpeg/ --strip=1
- export PATH=/tmp/ffmpeg:$PATH
- git clone https://github.com/WPO-Foundation/visualmetrics.git
- export VISUALMETRICS=$PWD/visualmetrics/visualmetrics.py
- ffmpeg -version
- firefox --version 2>/dev/null
- google-chrome --product-version
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

script:
- npm run lint
- npm test
- node ./bin/browsertime.js -b firefox -n 2 --timeouts.browserStart=60000 http://www.browsertime.net --preTask test/preposttasks/preSample.js --postTask test/preposttasks/postSample2.js
- node ./bin/browsertime.js -b chrome --skipHar -n 2 --timeouts.browserStart=60000 https://www.sitespeed.io
- node ./bin/browsertime.js -b chrome --experimental.nativeHar  --experimental.video -n 1 https://www.sitespeed.io
notifications:
  slack:
    secure: Bo/bgmtFVGj6I2XnkvERfGnoM+t73WQSsP5eMlGM0jhUSKPqIc7Hf2zjYil3amMY3awFnoA6prILcMBzyUURj3jc5VRsWBCf6aQZ3bM+xzAcuTMcoiAKS7Ru1HQj1WY8G7VycDWuNeF8dCT0kt2QhcSneAUQ0qqyclWjcOK22kw=
